config/routes.rb
Rails.application.routes.draw do

  root "pages#index"

  resources :family_members


  get  "/login", to: "sessions#new", as: "login"
  post "/login", to: "sessions#create"
  get  "/logout", to: "sessions#destroy", as: "logout"

  get  "/dashboard", to: "users#show", as: "user_dashboard"

  get "/errors/404", to: "errors#show", as: "error_404"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/family_member.rb
class FamilyMember < ApplicationRecord
  default_scope { order('first_name ASC') }
  before_validation :strip_and_downcase, only: [:first_name, :last_name]
  belongs_to :relationship

  validates_presence_of :first_name
  validates_presence_of :last_name
  validates_presence_of :birthdate
  validates_presence_of :relationship_id
  validates_uniqueness_of :first_name, scope: :last_name, case_sensitive: false

  def formatted_relationship
    relationship.rel_type.upcase
  end

  def raw_relationship
    relationship.rel_type if relationship
  end

  def age
    now = Date.today.to_date
    now.year - birthdate.year - (birthdate.to_date.change(year: now.year) >= now ? 1 : 0)
  end

  def days_until
    now = Date.today.to_date
    if birthdate.to_date.change(year: now.year) > now
      bd = birthdate.to_date.change(year: now.year)
      (bd - now).to_i
    else
      bd = birthdate.to_date.change(year: now.year + 1)
      (bd - now).to_i
    end
  end

  def self.sorted_by_days_until
    FamilyMember.all.sort_by(&:days_until)
  end

  private

  def strip_and_downcase
    self.first_name = self.first_name.strip.downcase unless self.first_name.nil?
    self.last_name = self.last_name.strip.downcase unless self.last_name.nil?
  end
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  has_many :family_members

  def self.from_family_member(input, type, member=nil)
    rel = find_or_initialize_by(rel_type: input[:raw_relationship].downcase)
    if rel.save && type == "create"
      input.delete :raw_relationship
      new_input = input.merge({ relationship_id: rel.id })
      FamilyMember.new(new_input)
    elsif rel.save && type == "update"
      input.delete :raw_relationship
      new_input = input.merge({ relationship_id: rel.id })
      member.assign_attributes(new_input)
      member
    end
  end


end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates_presence_of(:email)
  validates_uniqueness_of(:email)
  validates_presence_of(:password_digest)
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user, :require_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def require_user
    redirect_to error_404_path unless current_user
  end
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  def show
  end
end

app/controllers/family_members_controller.rb
class FamilyMembersController < ApplicationController
  before_action :require_user
  def index
    @family_members = FamilyMember.sorted_by_days_until
  end

  def new
    @fam = FamilyMember.new
  end

  def create
    fam = Relationship.from_family_member(family_member_params, "create")
    if fam.save
      flash[:success] = "New Person Created!"
      redirect_to family_members_path
    else
      flash.now[:danger] = "something went wrong!"
      render :new
    end
  end

  def edit
    @fam = FamilyMember.find(params[:id])
  end

  def update
    member = FamilyMember.find(params[:id])
    fam = Relationship.from_family_member(family_member_params, "update", member)
    if fam.save
      flash[:success] = "#{fam.first_name} updated!"
      redirect_to family_members_path
    end
  end

  def destroy
    if FamilyMember.delete(params[:id])
      flash[:warning] = "you deleted someone, i'm not sure who"
      redirect_to family_members_path
    end
  end

  private

  def family_member_params
    params.require(:family_member).permit(:first_name, :last_name, :birthdate, :relationship_id, :raw_relationship)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index    
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = "you're logged in!"
      redirect_to user_dashboard_path
    else
      flash.now[:danger] = "something went wrong!"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:danger] = "logged out!"
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/family_members/edit.html.erb
<%= render partial: "shared/fam_form", locals: { fam: @fam, button_text: "Update!" } %>

app/views/family_members/index.html.erb
<div class="container fm-index">
  <div class="row">
    <div class="col-md-3">
      <%= render partial: "shared/sidebar" %>
    </div>
    <div class="col-md-9">
      <% @family_members.each do |fam| %>
      <div class="card fam-card">
        <img src="http://placehold.it/250x250" class="fm-card-image" />
        <section class="profile-information">
          <p class="custom-text-title"><%= fam.first_name.capitalize %> <%= fam.last_name.capitalize %></p>
          <p class="custom-text-muted"><%= fam.formatted_relationship %></p>
          <section class="fam-links">
            <%= link_to "edit", edit_family_member_path(fam) %> |
            <%= button_to "delete", { action: :destroy, id: fam.id }, { method: :delete, class: "fam-delete-button"} %>
          </section>
          <p class="card-text"><%= fam.birthdate.strftime("%B %e, %Y") %></p>
          <p class="custom-text-muted"><%= fam.age %> years old</p>
          <p class="custom-text-muted"><span><%= fam.days_until %></span> days to go</p>
        </section>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/family_members/new.html.erb
<%= render partial: "shared/fam_form", locals: { fam: @fam, button_text: "Create!" } %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PresentTracker</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
</head>

<body>
  <%= render "shared/navbar" %>

  <% flash.each do |key, value| %>
  <div class="container">
    <div class="alert alert-<%= key %> alert-dismissible", role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      <%= value %>
    </div>
  </div>
  <% end %>

  <div class="main-container">
    <%= yield %>
  </div>

  <script>
  $('.alert').fadeIn(function() {
    setTimeout(function() {
      $('.alert').fadeOut();
    }, '3000');
  });
  </script>

</body>
</html>

app/views/shared/_fam_form.html.erb
<div class="col-sm-4 offset-sm-4 family-modal">
  <div class="card">
    <div class="card-header">
      Create Someone
    </div>
    <div class="card-block">
      <%= form_for fam do |f| %>
      <div class="form-group">
        <%= f.label :first_name, "first name" %>
        <%= f.text_field :first_name, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :last_name, "last name" %>
        <%= f.text_field :last_name, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :birthdate, "birthdate" %>
        <%= f.date_field :birthdate, id:"birthdate", class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :raw_relationship, "relationship" %>
        <%= f.text_field :raw_relationship, class: "form-control" %>
      </div>
      <div class="form-button">
        <%= f.submit button_text, class: "btn btn-outline-primary btn-block" %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-fixed-top navbar-light bg-faded">
  <div class="container">
    <a class="navbar-brand" href="/">Super Duper Present Tracking System</a>
    <ul class="nav navbar-nav pull-xs-right">
      <% if current_user %>
        <li class="nav-item">
          <%= link_to "Dashboard", user_dashboard_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Log Out", logout_path, class:"nav-link" %>
        </li>
        <% else %>
        <li class="nav-item">
          <%= link_to "Log In", login_path, class:"nav-link" %>
        </li>
        <% end %>
      </li>
    </ul>
  </div>
</nav>

app/views/shared/_sidebar.html.erb
<ul class="list-group">
  <li class="list-group-item"><%= link_to "create new", new_family_member_path %></li>
  <li class="list-group-item"><%= link_to "view all", family_members_path %></li>
</ul>

app/views/users/show.html.erb
<div class="container">
  <div class="col-md-3">
    <%= render partial: "shared/sidebar" %>
  </div>
  <div class="col-md-9">
    <h2>DASHBOARD!</h2>
  </div>
</div>